// client/src/components/EducationalCard.jsx
// Displays the LLM-generated educational summary about the 3D object

export default function EducationalCard({ summary, generatedFrom }) {
  if (!summary) return null;

  return (
    <div className="glass rounded-2xl p-6 animate-fade-in-up gradient-border">
      {/* Header */}
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-accent-violet/20 to-accent-cyan/20 flex items-center justify-center text-xl border border-accent-violet/20">
          📚
        </div>
        <div>
          <h3 className="text-sm font-semibold text-surface-50">
            Educational Summary
          </h3>
          <p className="text-xs text-surface-200/40">
            Generated by AI • {generatedFrom === 'image' ? 'From image' : 'From text prompt'}
          </p>
        </div>
      </div>

      {/* Summary Text */}
      <blockquote className="text-sm leading-relaxed text-surface-200/80 pl-4 border-l-2 border-primary-500/30">
        {summary}
      </blockquote>

      {/* Footer */}
      <div className="mt-4 flex items-center gap-2">
        <span className="px-2.5 py-1 text-xs rounded-full bg-primary-500/10 text-primary-300 border border-primary-500/20">
          🤖 Gemini 2.0 Flash
        </span>
        <span className="px-2.5 py-1 text-xs rounded-full bg-surface-800/60 text-surface-200/40 border border-surface-700/20">
          2-sentence format
        </span>
      </div>
    </div>
  );
}
